version: "3"

services:
  nb:
    image: "artiomn/nb-build-image"
    network_mode: host
    environment:
      - EXT_UID=1000
      - EXT_GID=1000
    # privileged: true
    working_dir: /usr/src/gb
    volumes:
      - .:/usr/src/gb
