// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "PhoneService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class PhoneServiceHandler : virtual public PhoneServiceIf {
 public:
  PhoneServiceHandler() {
    // Your initialization goes here
  }

  void findById(Phone& _return, const int32_t id) {
    // Your implementation goes here
    printf("findById\n");
  }

  void findAll(std::vector<Phone> & _return) {
    // Your implementation goes here
    printf("findAll\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<PhoneServiceHandler> handler(new PhoneServiceHandler());
  ::std::shared_ptr<TProcessor> processor(new PhoneServiceProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

