version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "1883:1883"
      - "5672:5672"
      - "8080:15672"
      - "1885:15675"
    command: "/bin/bash -c \"rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_mqtt rabbitmq_amqp1_0; rabbitmq-server\""
#    env_file:
#      - config/login.env
    volumes:
      - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro"
      - "./advanced.config:/etc/rabbitmq/advanced.config:ro"
