# UID, generated by capnp id.
@0xbed3aeae4f107525;

using CPP = import "/capnp/c++.capnp";
$CPP.namespace("our_system::capnp");

struct Tag {
    id @0 :UInt64;
    timestamp @1 :UInt64;
    recvTimestamp @2 :UInt64;

    value :union {
        int @3 :Int64;
        double @4: Float64;
        string @5: Text;
        bool @6: Bool;
        list @7: List(UInt8);
    }

    operation @8: Type = read;

    enum Type {
        read @0;
        write @1;
    }
}
