name: Build C++ code for Windows

on:
  workflow_dispatch:
  workflow_call:
  workflow_run:
    workflows: ['Build and push Docker images']
    branches: [master]
    types:
      - completed
  push:
    paths:
      - 'src/**/cpp/**'
      - '.github/workflows/cpp-windows-build.yml'
      - '!src/docker_images/**'

env:
  VCPKG_INSTALL_ROOT: $(Build.SourcesDirectory)/vcpkg
  VCPKG_ARCH: 'x64-windows'
  BUILD_TOOLSET_VERSION: '142'
  CMAKE_GENERATOR: 'Visual Studio 16 2019'


#defaults:
#  run:
#    working-directory: ./src

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v2
        with:
          arch: x64
      - name: Install Boost
        uses: MarkusJx/install-boost@v2.4.1
        id: install-boost
        with:
          # A list of supported versions can be found here:
          # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
          boost_version: 1.81.0
          # boost_install_dir: C:\some_directory
          platform_version: 2019
          toolset: msvc
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.2.*'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          # dir: '${{ github.workspace }}/example/'
          install-deps: 'true'
          modules: 'qtcharts qtwebengine'
          archives: 'qtbase qtsvg'
          cache: 'false'
          cache-key-prefix: 'install-qt-action'
          setup-python: 'true'
          tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
          set-env: 'true'
          tools-only: 'false'
          aqtversion: '==2.1.*'
          py7zrversion: '==0.19.*'
          extra: '--external 7z'
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          # ninja version to download. Default: 1.10.0
          version: 1.10.0
#      - name: Install vcpkg
#        run: |
#          git clone -q --depth 1 https://github.com/microsoft/vcpkg.git $(VCPKG_INSTALL_ROOT)
#          xcopy ./ports ./vcpkg/ports/ /S
#          Invoke-Expression -Command $(VCPKG_INSTALL_ROOT)/bootstrap-vcpkg.bat
#      - name: Install Apache Thrift
#        run: |
#          $(VCPKG_INSTALL_ROOT)/vcpkg.exe install --recurse --triplet $(VCPKG_ARCH) thrift
#         $(VCPKG_INSTALL_ROOT)/vcpkg.exe integrate install
      - name: Build with CMake
        uses: ashutoshvarma/action-cmake-build@master
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
        with:
          build-dir: ${{ runner.workspace }}/build
          source-dir: ./src
          cc: cl
          cxx: cl
          configure-options: -DBoost_INCLUDE_DIR=${{steps.install-boost.outputs.BOOST_ROOT}}/include\
             -DBoost_LIBRARY_DIRS=${{steps.install-boost.outputs.BOOST_ROOT}}/lib -DBoost_COMPILER=vc$(BUILD_TOOLSET_VERSION) \
             -G Ninja
          build-type: Debug
          run-test: false
