name: Build C++ code for Linux

on:
  # For the manual run.
  workflow_dispatch:
  # To run as dependent.
  workflow_call:
  push:
    paths:
      - 'src/**/cpp/**'
      - '.github/workflows/cpp-linux-build.yml'
      - '!src/docker_images/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building code
        run: ./build_dockerized.sh
