name: Build C++ code for Linux

on:
  push:
    paths:
      - 'src/**/cpp/**'
      - '!src/docker_images/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building code
        run: ./build_dockerized.sh
