name: Build and push Docker images

on:
  push:
    paths:
      - 'src/docker_images/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: artiomn
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build main build image
        working-directory: ./src/docker_images/build_image
        run: ./build.sh -p
      - name: Build Qt Creator image
        working-directory: ./src/docker_images/qt_creator_image
        run: ./build.sh -p

